version: '3.9'

services:
  app:
    build: .
    container_name: integration_retailCRM
    ports:
      - "8880:8880"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8880 --reload
